#!/bin/bash

cp -r /opt/esm/.cime/* $HOME/.cime
cp /opt/esm/config_pes.xml /opt/esm/archive/config_pes.xml
sed -i -e "s/-1/-$SLURM_JOB_NUM_NODES/g" /opt/esm/archive/config_pes.xml

cd /opt/esm/my_sandbox/cime/scripts
./create_newcase --case /opt/esm/archive/cases/$CASENAME --compset $COMPSET --res $RES --machine container --run-unsupported --handle-preexisting-dirs r --pesfile /opt/esm/archive/config_pes.xml

cd /opt/esm/archive/cases/$CASENAME

./xmlchange STOP_N=1
./xmlchange STOP_OPTION=nmonths

./case.setup
./case.build --skip-provenance-check

mkdir -p /opt/esm/work/$CASENAME/run/timing/checkpoints

./check_input_data --download
./check_case

